### ISSUE TITLE
akashlytics-provider-proxy

### ISSUE THREAD

**Issue by berelton** [maxmaxlabs/cloudmos-deploy#106]
https://github.com/Akashlytics/akashlytics-deploy/pull/32/files#diff-8d84606c12e363cdd5b64f8164f3749e38d1472679bf557bdaca31054a5a233d

Hi folks, where I can find akashlytics-provider-proxy binary source code?

**Comment by baktun14** [comment]
Hi, it's currently in another repo but it simply forwards the calls to the providers since we can't do it in chrome.
