### ISSUE TITLE
Akashlytics Dash

### ISSUE THREAD

**Issue by okshock** [maxmaxlabs/cloudmos-deploy#108]
Hey Guys,  Forgive me for my ignorance but I can't wrap my head around this dashboard.  How do I know if my node is active and generating a return?  THanks!  
 is:issue is:open Network: Mainnet  Node: akash-node.cloudmos.io 125ms | Balance: $0.01 akash138he.....g6eftf Certificate Serial: 1631213900974000 20.95 AKT 693.67 AKT Balance: 0.01 AKT $0.01 Escrow: 20.95 AKT $6.74 Rewards: 0.27 AKT $0.09 Staked: 693.67 AKT $222.90 Unbondings: 0 AKT Total: 714.89 AKT $229.72 Network Capacity CPU 674 CPU / 3738 CPU RAM 747.2 GiB / 17.7 TiB STORAGE 7.2 TiB / 229.1 TiB Active Deployments 1.5 vcpu 5.0 GiB 8.0 GiB Craft   - 5003162 Balance:  5 AKT Spent:  0 AKT Leases: GSEQ: 1OSEQ: 1Name: d3akash.cloud 1 vcpu 1.0 GiB 3.0 GiB 4962259 Time left:  ~3 months Spent:  5 AKT Leases: GSEQ: 1OSEQ: 1Name: supernaut.ddns.net 1 vcpu 1.0 GiB 1.0 GiB 2596227 Balance:  5 AKT Spent:  0 AKT Leases: GSEQ: 1OSEQ: 1Name: provider.provider-0.prod.sjc1.akash.pub 1 vcpu 1.0 GiB 1.0 GiB 2582363 Balance:  5.95 AKT Spent:  0 AKT Leases: GSEQ: 1OSEQ: 1Name: provider.provider-0.prod.ams1.akash.pub v0.15.0 beta Akash Logo

**Comment by baktun14** [comment]
Hi, not sure I understand your question.
