### ISSUE TITLE
Is there a way copy my Akash address from the app?

### ISSUE THREAD

**Issue by YakovL** [maxmaxlabs/cloudmos-deploy#110]
After creating a wallet from the seed, I've got an address. I wonder, is there a way to copy it? Writing 39-char address is not very handy. At least the Accounts interface doesn't provide any possibility to copy it:

![image](https://user-images.githubusercontent.com/1131924/191566626-4d899f54-dbf9-46cf-9a24-6034715b1184.png)

**Comment by Redm4x** [comment]
Hi, you can copy your address by clicking on it on the right of the balance.
![image](https://user-images.githubusercontent.com/2829180/191575832-739640d6-7e63-4467-8b83-3edd930b007b.png)

**Comment by YakovL** [comment]
ah, right, didn't get it since the icon only appears on hover. Thanks!
