### ISSUE TITLE
Events page not updating

### ISSUE THREAD

**Issue by RobotPirateNinja** [maxmaxlabs/cloudmos-deploy#111]
I can't seem update deployments.  It doesn't show any events, and new containers pushed out to DockerHub are not being pulled.  I seem to have to recreate a deployment, and then it works for one update, then no more.

**Comment by Redm4x** [comment]
Hi, can you share your SDL? Are you using persistent storage by any chance?

**Comment by RobotPirateNinja** [comment]
No, no persistent storage.   Maybe it's just a provider that goes away?  I'm getting a 500 error (manifest version validation failed) and the "group" icon just keeps spinning on the "Leases" tab.  It doesn't resolve...and I can't bring up logs.

So I can't update the deployment.  I have the *exact same* SDL file deployed on another place, so the issue isn't there.

**Comment by RobotPirateNinja** [comment]
Hrrrm...interesting.....getting some curious behavior. 

So...I failed with manifest using version .18 of a container.  It didn't get pushed out.   So then, I can't try and 're-push' the same manifest (*the trx won't fire*) once I comes back.   So I'm just versioning my container and moving along....

But with that, now I'm seeing that my provider is failing to spin up a node as all their CPU is already being used....

Anyway, apologies.  I really like this tool.  Just trying to understand why/'how some of this stuff is failing.

**Comment by RobotPirateNinja** [comment]
I think I may just need to reserve a larger chunk of CPU/change providers.  The provider is *showing* that my 0.1 is still "available" but it doesn't seem to be able to allocate for it.
