### ISSUE TITLE
Syncing of nodes

### ISSUE THREAD

**Issue by alijnmerchant21** [maxmaxlabs/cloudmos-deploy#113]
I'm using Cloudmos to deploy nodes on Akash. Let us say I'm deploying an Osmosis node.

When I create a deployment, the node starts syncing and reaches to a certain percentage, let's say 56%.

When I go back to the dashboard and come back to Osmosis deployment - it is again back on 17%.

Is this an expected behavior? As in - the user is not expected to go back while the node is syncing?

**Comment by baktun14** [comment]
This is the behavior of the node you're running, not the Cloudmos app. I think something may be wrong with the docker image of the node.

**Comment by alijnmerchant21** [comment]
The same thing happens with other images + providers as well. I'll investigate this further. Thanks!
