### ISSUE TITLE
Shell tab just displays loading bar and never loads a usable shell window

### ISSUE THREAD

**Issue by bananocraft-miner82** [maxmaxlabs/cloudmos-deploy#115]
Not sure what would help here exactly - the deployments that I have that are affected are MongoDB images and a custom Minecraft server in a docker container.

Navigating into the lease and clicking the Shell tab results in the loading bar below the tab caption just spinning around with the Shell window never populating. The command box at the bottom can be clicked into and typed in, but submitting displays nothing.
![Screenshot 2022-12-01 154537](https://user-images.githubusercontent.com/105229999/205082516-3c8b608a-d50f-49fc-88e9-f557ce139519.jpg)

**Comment by baktun14** [comment]
Hey, is the container working and reachable with the uri?

**Comment by bananocraft-miner82** [comment]
Hi, the container is working just fine - it's a Minecraft server and I can usually shell into it via the CLI.

**Comment by bananocraft-miner82** [comment]
The Mongo databases are also working just fine.

**Comment by baktun14** [comment]
Ok weird, what it does is it sends a simple `ls` just to make sure it returns something in order to test the connection.
