### ISSUE TITLE
Expired Deployment Certificate Manifest Error Message

### ISSUE THREAD

**Issue by 2acoin** [maxmaxlabs/cloudmos-deploy#117]
The message displayed by the CloudMOS app when a deployment certificate has expired is not very helpful.

Currently, the message displayed during the deployment of the manifest file is (see attached image).
![socket_hang_up](https://user-images.githubusercontent.com/36861403/212419222-64b1aca4-648d-4a7f-a951-b3fa0402f25f.png)

The message should be better defined so that it is easier for the user to understand the cause of the error. I had to go into debug mode to determine the cause and discovered that my deployment certificate was over a year old and expired.

**Comment by 2acoin** [comment]
Most likely, I should have never been allowed to get to the level of submitting a manifest when my deployment certificate was expired. There should be some checks to ensure the deployment certificate was not in an expired state long before allowing me to submit a deployment for bidding.

**Comment by baktun14** [comment]
Hey, the error message is from the provider itself, not our app so we don't have much control over it. However, I don't think we check for certificate date, so good thing to point out. Thanks
