### ISSUE TITLE
AKASH wallet

### ISSUE THREAD

**Issue by sabba380** [maxmaxlabs/cloudmos-deploy#76]
Hi .. im getting error when i try mining PKT on AKASH wallet and the error message "Error while sending manifest to provider. Status code was not success (500) : post failed: Post "http://10.80.162.147:26657": EOF"

**Comment by Redm4x** [comment]
Hi, this is usually an issue with the provider itself. The equinix providers have been having this issue a lot recently. You could try another povider to see if you get the same error. 

There is a **pkt-mining** channel in the Akash discord server where you could ask what provider other miners are using.
https://discord.com/channels/747885925232672829/878151333046255627
