### ISSUE TITLE
PKT Manifest Issue

### ISSUE THREAD

**Issue by YankeeCobra** [maxmaxlabs/cloudmos-deploy#79]
Anyone getting an error when trying to deploy PKT via 'deploy.yml' on nick-casa's PKT mining doc. (see below) I have tried manually submitting, made changes, etc. and wasted some AKT dollars on this. I previously had this running for a few months flawlessly and all of a sudden the Akash deployment started erroring out. Anyone have an updated 'deploy.yml'? Anyone also know the process to get credits for wasted AKT?

**Nick-Casa Doc:** https://github.com/nick-casa/Akash-PKT-Mining

I also tried to deploy the template by cryptocoffee that is included in the dashboard. No luck there either!

**Error:** Error while sending manifest to provider. Status code was not success (500) : post failed: Post "http://10.80.162.147:26657": EOF

**Comment by baktun14** [comment]
This issue is related... https://github.com/Akashlytics/akashlytics-deploy/issues/76
