### ISSUE TITLE
Idea: GitHub Integration w/ repo of deploy files

### ISSUE THREAD

**Issue by Reecepbcups** [maxmaxlabs/cloudmos-deploy#96]
Here is an idea I had today, it is possible it does not make sense but wanted to share it either way in case you all like the idea.
This is more of a nice to have:

### Problem:
As I have been deploying more with Akash, I find myself having deploy files everywhere. Discord, each GitHub project, etc.
Once I do find the file, I figure out I didn't use the ENV variables I wanted and still find myself having to go google it.

### Solution:
My idea here is that you could login with GitHub & select a public/private template repository of your deploy.yaml files.
This way you have 1 central place and can easily access it from within the deploy panel itself. 
You can then scroll through, select and/or copy paste your yaml file & deploy from that.

### Rough flow
<img src="https://user-images.githubusercontent.com/31943163/170605186-4388dae1-c745-4768-b138-8d3c5871f366.png" width="500" height="350">

- User signs in and it saves their github access token to the app
- A new page opens up showcasing their repositories (or an input link for the git repo, which ever is easiest). 
    *- Could allow favorites for multiple in case you do work with multiple orgs*
    *- If a user already has an access token/set a repository, they do not have to do this every time. Just a way to add new repos*

- Within the deploy tool, they can scroll through the files within the repo (expand/collapse folders) & click on a YAML file.
![image](https://user-images.githubusercontent.com/31943163/170606516-bb57eec2-6d55-4380-ad62-d6e284888b69.png)

- This would open it in preview mode, then you can edit it, and then deploy/get bids

**Comment by baktun14** [comment]
Hey Reece! Yea for sure that sounds like a great idea. I'll put it in our nice to have task list. Or if you or someone wants to implement it.

**Comment by sascha1337** [comment]
LGTD
Lets get this done
